//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipies.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CookingProduct
    {
        public int Id { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> Product_Id { get; set; }
        public Nullable<int> Step_Id { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Step Step { get; set; }
    }
}
