//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipies.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.CookingProducts = new HashSet<CookingProduct>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int QuantityType { get; set; }
    
        public virtual ICollection<CookingProduct> CookingProducts { get; set; }
    }
}
