//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipies.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public int Id { get; set; }
        public int OrderOfPrecedence { get; set; }
        public decimal PreparationTime { get; set; }
        public Nullable<int> Recepie_Id { get; set; }
        public string Description { get; set; }
    
        public virtual Recipy Recipy { get; set; }
    }
}
