//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recipies.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Comments = new HashSet<Comment>();
            this.Recipies = new HashSet<Recipy>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
        public string NickName { get; set; }
        public string SessionKey { get; set; }
        public string AuthCode { get; set; }
    
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Recipy> Recipies { get; set; }
    }
}
