//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reciepes.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Step
    {
        public Step()
        {
            this.CookingProducts = new HashSet<CookingProduct>();
        }
    
        public int Id { get; set; }
        public int OrderOfPrecedence { get; set; }
        public System.DateTime PreparationTime { get; set; }
        public int Degrees { get; set; }
        public Nullable<int> Recepie_Id { get; set; }
        public Nullable<int> StepAction_Id { get; set; }
    
        public virtual ICollection<CookingProduct> CookingProducts { get; set; }
        public virtual Recipy Recipy { get; set; }
        public virtual StepAction StepAction { get; set; }
    }
}
